import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased flex flex-col flex-grow`}
      >
        <header className="overflow-auto p-2 m-3 rounded-3xl bg-olive-200 dark:bg-olive-800">
          <NavBar />
        </header>
        <main className="min-h-screen p-8 w-full md:w-3xl self-center-safe">
          {children}
        </main>
        <footer className="flex flex-col gap-2 text-sm text-center rounded-3xl p-2 m-3 bg-olive-200 dark:bg-olive-800">
          <p>
            Licensed under the 3-BSD-Clause license. Built with Next.js and
            TypeScript.
          </p>
          <a href="#">Scroll to top</a>
        </footer>
      </body>
    </html>
  );
}
